# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shenvy < Formula
  desc "Securely manage environment variables with E2EE."
  homepage "https://shenvy.net"
  version "0.1.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Shenvy/shenvy-cli-dist/releases/download/v0.1.14/shenvy_darwin_amd64.tar.gz"
      sha256 "5f3bdeb84663e2d51dbecb4d0b2ebc626ab904415cc1e2b1eb1e0d032a9548d2"

      define_method(:install) do
        bin.install "shenvy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Shenvy/shenvy-cli-dist/releases/download/v0.1.14/shenvy_darwin_arm64.tar.gz"
      sha256 "69f989d1d1f5af455fade86ab89a9549414f6ed39c34ac0e3f36852a7410cfaf"

      define_method(:install) do
        bin.install "shenvy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shenvy/shenvy-cli-dist/releases/download/v0.1.14/shenvy_linux_amd64.tar.gz"
      sha256 "7de3b2ff60e63fed7c491bac2393ca62bf0a6560890ff5c5164255b95d30ca19"
      define_method(:install) do
        bin.install "shenvy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shenvy/shenvy-cli-dist/releases/download/v0.1.14/shenvy_linux_arm64.tar.gz"
      sha256 "d0610be6cb92aeed5a4f8d1ee9b6e232590089844aad1c6c78b2fb2bd4db89c1"
      define_method(:install) do
        bin.install "shenvy"
      end
    end
  end

  test do
    system "#{bin}/shenvy version"
  end
end
