# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shenvy < Formula
  desc "Securely manage environment variables with E2EE."
  homepage "https://shenvy.net"
  version "0.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Shenvy/shenvy-cli-dist/releases/download/v0.1.11/shenvy_darwin_amd64.tar.gz"
      sha256 "2db25f5b4ec61fceb8d0efda017a7f28e8cb0991f50a0fb85d34dbbb00908c70"

      define_method(:install) do
        bin.install "shenvy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Shenvy/shenvy-cli-dist/releases/download/v0.1.11/shenvy_darwin_arm64.tar.gz"
      sha256 "4bf0c6f51844a587ec26d20f7c84ae1a1a54cfeecb9d27354521335e40af4b85"

      define_method(:install) do
        bin.install "shenvy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shenvy/shenvy-cli-dist/releases/download/v0.1.11/shenvy_linux_amd64.tar.gz"
      sha256 "9f65b84678932436260a2713232db38de1101115cfac4130cae3c3d0c235b052"
      define_method(:install) do
        bin.install "shenvy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shenvy/shenvy-cli-dist/releases/download/v0.1.11/shenvy_linux_arm64.tar.gz"
      sha256 "d257b7d556e8ba7d46b77b7148b7e480f3831a26c11498033b3e4a964c453208"
      define_method(:install) do
        bin.install "shenvy"
      end
    end
  end

  test do
    system "#{bin}/shenvy version"
  end
end
